language: node_js # 언어는 node_js
node_js:
  - "10"
before_deploy: # 배포하기전 하는 작업들
  - rm -rf node_modules # travis가 설치한 node_moduels를 삭제
deploy: # 배포
  - provider: codedeploy
    revision_type: github
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    application: hj-entrant-codedeploy-app # AWS 배포 애플리케이션
    deployment_group: hj-entrant-codedeploy-group # AWS 배포 애플리케이션에 만들어져 있는 배포 그룹
    region: ap-northeast-2
    on:
      repo: academey/ridi-new-entrant-web
      branch: master
#  - provider: codedeploy # AWS CodeDeploy를 의미
#    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
#    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
#    bucket: hj-entrant-bucket # AWS CodeDeploy가 다운로드 받은 버킷
#    key: ridi-new-entrant-web.zip # 해당 버킷에 저장되어 있는 파일 이름
#    bundle_type: zip # 버킷에 저장되어 있는 파일의 확장자
#    application: hj-entrant-codedeploy-app # AWS 배포 애플리케이션
#    deployment_group: hj-entrant-codedeploy-group # AWS 배포 애플리케이션에 만들어져 있는 배포 그룹
#    region: ap-northeast-2
#    wait-until-deployed: true
#    on:
#      repo: academey/ridi-new-entrant-web
#      branch: master
notifications:
  email:
    recipients:
      - hjpark@ridi.com
