version: '3'
services:
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - server
      - composed-maria-db
  composed-maria-db:
    container_name: composed-maria-db
    restart: always
    image: mariadb
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER={DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
      - ./src/database/seeders/init.sql:/data/application/init.sql
    ports:
      - "3306:3306"
  server:
    container_name: server
    restart: always
    build: . # Dockerfile이 위치한 경로
    ports:
      - "8080:8080" # 연결할 포트
    volumes:
      - /app/node_modules/ # /app/node_modules를 비워줌
    environment: # 환경변수 설정
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - composed-maria-db
